#define TFT_SWAP_COLOR              0x7FFF
#define TFT_UNCHANGED               0xFFFE
#define TFT_BLACK                   0x0000
#define TFT_NAVY                    0x000F
#define TFT_DARKGREEN               0x03E0
#define TFT_DARKCYAN                0x03EF
#define TFT_MAROON                  0x7800
#define TFT_PURPLE                  0x780F
#define TFT_OLIVE                   0x7BE0
#define TFT_DARKGREY                0x7BEF
#define TFT_LIGHTGREY               0xD69A
#define TFT_BLUE                    0x001F
#define TFT_GREEN                   0x07E0
#define TFT_CYAN                    0x07FF
#define TFT_RED                     0xF800
#define TFT_MAGENTA                 0xF81F
#define TFT_YELLOW                  0xFFE0
#define TFT_WHITE                   0xFFFF
#define TFT_ORANGE                  0xFDA0
#define TFT_GREENYELLOW             0xB7E0
#define TFT_PINK                    0xFE19
#define TFT_LIGHTPINK               0xFC9F
#define TFT_BROWN                   0x9A60
#define TFT_GOLD                    0xFEA0
#define TFT_SILVER                  0xC618
#define TFT_SKYBLUE                 0x867D
#define TFT_VIOLET                  0x915C
#define TFT_TRANSPARENT             0x0120
#define TFT_SLIVE                   0xC618
#define TFT_MAGENTA                 0xF81F
#define TFT_TEAL                    0x0410
#define TFT_GHOSTWHITE              0xFFDF
#define TFT_WHITESMOKE              0xF7BE
#define TFT_GAINSBORO               0xDEFB
#define TFT_DIMGRAY                 0x6B4D
#define TFT_LIGHTGRAY               0xD69A
#define TFT_LIGHTSLATEGRAY          0x7453
#define TFT_SLATEGRAY               0x7412
#define TFT_DARKSLATEGRAY           0x2A69
#define TFT_PALEGOLDENROD           0xEF55
#define TFT_FLORALWHITE             0xFFDE
#define TFT_GOLDENRODYELLOW         0xFFDA
#define TFT_SADDLEBROWN             0x8A22
#define TFT_SIENNA                  0xA285
#define TFT_OLDLACE                 0xFFBC
#define TFT_PAPAYAWHIP              0xFF7A
#define TFT_BLANCHEDALMOND          0xFF59
#define TFT_MOCCASIN                0xFF36
#define TFT_LIGHTSLATEBLUE          0x839F
#define TFT_DARKSLATEBLUE           0x49F1
#define TFT_ROYALBLUE               0x435C
#define TFT_DARKBLUE                0x0011
#define TFT_MIDNIGHTBLUE            0x18CE
#define TFT_CORNFLOWERBLUE          0x64BD
#define TFT_MEDIUMBLUE              0x0019
#define TFT_POWDERBLUE              0xB71C
#define TFT_STEELBLUE               0x4416
#define TFT_SKYBLUE                 0x867D
#define TFT_LIGHTSKYBLUE            0x867F
#define TFT_LIGHTSTEELBLUE          0xB63B
#define TFT_LIGHTBLUE               0xAEDC
#define TFT_CADETBLUE               0x5CF4
#define TFT_PALETURQUOISE           0xAF7D
#define TFT_MEDIUMTURQUOISE         0x4E99
#define TFT_DARKTURQUOISE           0x067A
#define TFT_TURQUOISE               0x471A
#define TFT_DARKSEAGREEN            0x8DF1
#define TFT_SEAGREEN                0x2C4A
#define TFT_PALEGREEN               0x9FD3
#define TFT_SPRINGGREEN             0x07EF
#define TFT_MEDIUMSEAGREEN          0x3D8E
#define TFT_LIGHTSEAGREEN           0x2595
#define TFT_LIGHTGREEN              0x9772
#define TFT_LAWNGREEN               0x7FE0
#define TFT_MEDIUMSPRINGGREEN       0x07D3
#define TFT_LIMEGREEN               0x3666
#define TFT_YELLOWGREEN             0x9E66
#define TFT_FORESTGREEN             0x2444
#define TFT_CHARTREUSE              0x7FE0
#define TFT_OLIVEDRAB               0x6C64
#define TFT_DARKOLIVEGREEN          0x5345
#define TFT_DARKKHAKI               0xBDAD
#define TFT_LIGHTGOLDENROD          0xEEF0
#define TFT_GOLD                    0xFEA0
#define TFT_GOLDENROD               0xDD24
#define TFT_DARKGOLDENROD           0x8B31
#define TFT_ROSYBROWN               0xBC71
#define TFT_INDIANRED               0xCAEB
#define TFT_BURLYWOOD               0xEE32
#define TFT_WHEAT                   0xF6F6
#define TFT_TAN                     0xD5B1
#define TFT_CHOCOLATE               0xCB23
#define TFT_FIREBRICK               0xB104
#define TFT_SALMON                  0xFC0E
#define TFT_LIGHTSALMON             0xFD0F
#define TFT_DARKORANGE              0xFBE0
#define TFT_LIGHTCORAL              0xF410
#define TFT_CORAL                   0xFBEA
#define TFT_TOMATO                  0xEAE8
#define TFT_ORANGERED               0xFA20
#define TFT_DARKRED                 0x8800
#define TFT_ROUGE                   0xC000
#define TFT_CRIMSON                 0xD8A7
#define TFT_DEEPPINK                0xF8B2
#define TFT_HOTPINK                 0xFB56
#define TFT_PALEVIOLETRED           0xDB92
#define TFT_VIOLETRED               0xD112
#define TFT_MAGENTA                 0xF81F
#define TFT_DARKMAGENTA             0x8811
#define TFT_ORCHID                  0xDB9A
#define TFT_PLUM                    0xDD1B
#define TFT_MEDIUMORCHID            0xBABA
#define TFT_DARKORCHID              0x9999
#define TFT_MEDIUMVIOLETRED         0xC0B0
#define TFT_DARKVIOLET              0x901A
#define TFT_BLUEVIOLET              0x895C
#define TFT_MEDIUMPURPLE            0x939B
#define TFT_THISTLE                 0xDDFB
#define TFT_ANTIQUEGOLD             0xDE31
#define TFT_AGEDPAPER               0xED4A
#define TFT_PEACHORANGE             0xFE73